### ISSUE TITLE
tutorial-03: uwsgitop not installed

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/training#13]
[Step 7](https://github.com/inveniosoftware/training/tree/master/03-infrastructure-tour#step-7-access-the-web-applications-uwsgi) includes the use of ``uwsgitop`` but it doesn't seem to be installed in the docker image.

**Comment by slint** [comment]
Hm, did you generate it after https://github.com/inveniosoftware/cookiecutter-invenio-instance/commit/ca13a023d1615ce1e1ce69d46d06e33173bf3a16 was merged?

EDIT: `v3.1` branch on cookiecutter updated

**Comment by lnielsen** [comment]
No :-)
