### ISSUE TITLE
tutorial-06: reorganize tutorial with steps

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/training#18]
The README doesn't follow the same structure as the previous tutorials. I would expect a couple of steps with a bit of text and images. I think most of it can just be taken from the presentation.

- Step 1: Inspect project structure
- Step 2: Initialize the git repository
- Step 3: Build the documentation
- Step 4: Running tests
- Step 5: End-to-end testing
- Step 6: Fix the failing test
- Step 7: Installing a new Python dependency

**Comment by kpsherva** [comment]
done
