### ISSUE TITLE
tutorial-07: bootstrap fix

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/training#25]
- [Bootstrap exercise](https://github.com/inveniosoftware/training/tree/master/07-data-models-new-field#bootstrap-exercise) should be an optional step (only if you messed up the previous step.
- Commands should not assume a starting directory: ``cd 03-add-new-field``-> ``cd ~/src/training/03-add-new-field/`` (otherwise users cannot just copy it in the terminal)

**Comment by lnielsen** [comment]
Also, the folder is no longer 03-add-new-field

**Comment by lnielsen** [comment]
07-data-models-new-field

**Comment by zzacharo** [comment]
Already fixed!
