### ISSUE TITLE
./start-from.sh doesn't apply chosen state

### ISSUE THREAD

**Issue by AoNoOokami** [inveniosoftware/training#51]
xxx@xxx:src $ ls -l
total 8
drwxr-xr-x  31 xxx  staff   992  5 Sep 11:40 my-site
drwxr-xr-x   8 xxx  staff   256  5 Sep 10:32 my_site
-rw-r--r--   1 xxx  staff  2737  5 Sep 11:17 setup.py
drwxr-xr-x  26 xxx  staff   832  4 Sep 14:23 training

After applying ./start-from.sh 09-deposit-form I have both my-site and my_site in src folder and the application doesn't work properly.

After studying ./start-from.sh I noticed an error at line 38:
replace 

cp -R "$invenio_training_folder/$exercise_tutorial_folder/solution/my-site/" "$invenio_src_folder"

by

cp -R "$invenio_training_folder/$exercise_tutorial_folder/solution/my-site/" "$invenio_instance_folder"

and it'll work fine

**Comment by diegodelemos** [comment]
Closed by https://github.com/inveniosoftware/training/pull/52, thanks!
